# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'fish.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1035, 838)
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(0, 0, 1031, 841))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("fish.jpg"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(320, 20, 391, 61))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(70, 150, 181, 41))
        self.label_3.setStyleSheet("font: 75 16pt \"Comic Sans MS\";color:rgb(255, 255, 255)")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(70, 240, 181, 41))
        self.label_4.setStyleSheet("font: 75 16pt \"Comic Sans MS\";color:rgb(255, 255, 255)")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setGeometry(QtCore.QRect(70, 330, 181, 41))
        self.label_5.setStyleSheet("font: 75 16pt \"Comic Sans MS\";color:rgb(255, 255, 255)")
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(Form)
        self.label_6.setGeometry(QtCore.QRect(70, 420, 181, 41))
        self.label_6.setStyleSheet("font: 75 16pt \"Comic Sans MS\";color:rgb(255, 255, 255)")
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(Form)
        self.label_7.setGeometry(QtCore.QRect(70, 510, 181, 41))
        self.label_7.setStyleSheet("font: 75 16pt \"Comic Sans MS\";color:rgb(255, 255, 255)")
        self.label_7.setObjectName("label_7")
        self.len1 = QtWidgets.QLineEdit(Form)
        self.len1.setGeometry(QtCore.QRect(270, 150, 321, 41))
        self.len1.setStyleSheet("font: 75 18pt \"MS Shell Dlg 2\";color:rgb(85, 85, 255)")
        self.len1.setObjectName("len1")
        self.len2 = QtWidgets.QLineEdit(Form)
        self.len2.setGeometry(QtCore.QRect(270, 240, 321, 41))
        self.len2.setStyleSheet("font: 75 18pt \"MS Shell Dlg 2\";color:rgb(85, 85, 255)")
        self.len2.setObjectName("len2")
        self.len3 = QtWidgets.QLineEdit(Form)
        self.len3.setGeometry(QtCore.QRect(270, 330, 321, 41))
        self.len3.setStyleSheet("font: 75 18pt \"MS Shell Dlg 2\";color:rgb(85, 85, 255)")
        self.len3.setObjectName("len3")
        self.height = QtWidgets.QLineEdit(Form)
        self.height.setGeometry(QtCore.QRect(270, 430, 321, 41))
        self.height.setStyleSheet("font: 75 18pt \"MS Shell Dlg 2\";color:rgb(85, 85, 255)")
        self.height.setObjectName("height")
        self.width = QtWidgets.QLineEdit(Form)
        self.width.setGeometry(QtCore.QRect(270, 520, 321, 41))
        self.width.setStyleSheet("font: 75 18pt \"MS Shell Dlg 2\";color:rgb(85, 85, 255)")
        self.width.setObjectName("width")
        self.estimate = QtWidgets.QPushButton(Form)
        self.estimate.setGeometry(QtCore.QRect(300, 620, 241, 51))
        self.estimate.setStyleSheet("font: 75 18pt \"MS Shell Dlg 2\";color:rgb(255, 0, 0)")
        self.estimate.setObjectName("estimate")
        self.display = QtWidgets.QLineEdit(Form)
        self.display.setGeometry(QtCore.QRect(180, 720, 241, 71))
        self.display.setStyleSheet("font: 75 18pt \"MS Shell Dlg 2\";color:rgb(255, 0, 0)")
        self.display.setObjectName("display")
        self.label_8 = QtWidgets.QLabel(Form)
        self.label_8.setGeometry(QtCore.QRect(530, 720, 361, 71))
        self.label_8.setStyleSheet("font: 75 16pt \"Comic Sans MS\";color:rgb(255, 255, 255)")
        self.label_8.setObjectName("label_8")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Fish Weight Estimation"))
        self.label_2.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:18pt; font-weight:600; color:#ffff00;\">Fish Weight Estimation</span></p></body></html>"))
        self.label_3.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:18pt;\">Length_1</span></p></body></html>"))
        self.label_4.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:18pt;\">Length_2</span></p></body></html>"))
        self.label_5.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:18pt;\">Length_3</span></p></body></html>"))
        self.label_6.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:18pt;\">Height</span></p></body></html>"))
        self.label_7.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:18pt;\">Width</span></p></body></html>"))
        self.estimate.setText(_translate("Form", "Estimate Weight"))
        self.label_8.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:22pt; font-weight:600;\">Calculated Weight</span></p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
